/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.shalomander.jda_bot;

import org.junit.Test;
import static org.junit.Assert.*;

public class JDABotTest {
    @Test public void testNewJDABot() {
        JDABot jdaBot = new JDABot("");
        assertTrue("jdaBot should be instance of JDABot class", jdaBot instanceof JDABot);
    }
}
